### ISSUE TITLE
哇 这个是中国人做的吗？

### ISSUE THREAD

**Issue by zapline** [vizee/echo#2]
感觉好牛比啊  膜拜膜拜

**Comment by vizee** [comment]
Ni keyi shuo yingyu ma?

**Comment by AngryPowman** [comment]
I think this is very helpful

**Comment by zapline** [comment]
waaaaaaaaah！niubility！Is this a log library made by chinese people？so cooool！

**Comment by vizee** [comment]
Kan bu dong!

**Comment by GongT** [comment]
I think this is very helpful
